export const ROUTES = {
  LANDING:               '/',
  STUDENT_REGISTER:      '/register',
  ADMIN_LOGIN:           '/admin/login',
  STUDENT_HOME:          '/home',
  ELECTION_DETAIL:       '/election/:id',
  VOTE_CONFIRM:          '/vote/:electionId/:candidateId',
  MY_VOTES:              '/my-votes',
  ADMIN_DASHBOARD:       '/admin',
  ADMIN_ELECTIONS:       '/admin/elections',
  ADMIN_CREATE_ELECTION: '/admin/elections/create',
  ADMIN_CANDIDATES:      '/admin/candidates',
  ADMIN_ADD_CANDIDATE:   '/admin/candidates/add',
  ADMIN_STUDENTS:        '/admin/students',
  ADMIN_MANAGE_ADMINS:   '/admin/manage-admins',
  ADMIN_RESULTS:         '/admin/results',
};
